# Generated by Django 5.2 on 2025-04-27 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome Social')),
                ('profession', models.CharField(choices=[('DR', 'Médico(a)'), ('NR', 'Enfermeiro(a)'), ('PS', 'Psicólogo(a)'), ('DT', 'Dentista'), ('NT', 'Nutricionista')], max_length=2, verbose_name='Profissão')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissional de Saúde',
                'verbose_name_plural': 'Profissional de Saúde',
                'ordering': ['social_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('patient_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome do Paciente')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='healthcare.healthprofessional', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-date'],
            },
        ),
    ]
