name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Trigger DigitalOcean Build
      run: |
        APP_ID=$(doctl apps list --format ID,Spec.Name | grep "healthcare-api" | awk '{print $1}')
        doctl apps create-deployment $APP_ID